<template><div><h1 id="importing-an-existing-google-cloud-platform-account" tabindex="-1"><a class="header-anchor" href="#importing-an-existing-google-cloud-platform-account"><span>Importing an Existing Google Cloud Platform Account</span></a></h1>
<p>To import a GCP storage account, you will need to create a service account with access to the storage and create a key pair for the account.</p>
<ol>
<li>
<p>From the main Google Cloud menu, under the <strong>IAM &amp; Admin</strong> section, navigate to <strong>Service Accounts</strong>.<br>
<img src="@source/en/storage/img/import_gcp-01.png" alt="Service accounts in menu"></p>
</li>
<li>
<p>At the top of the screen, click <strong>Create Service Account</strong> and fill in the information for the account. The Service Account ID will be auto-generated by default, but you can re-generate it or manually enter your own desired value.<br>
<img src="@source/en/storage/img/import_gcp-02.png" alt="Create account button">
<img src="@source/en/storage/img/import_gcp-03.png" alt="Service account details"></p>
</li>
<li>
<p>After creating the user, click on its username in the list, and navigate to the <strong>Keys</strong> tab. From here, click the <strong>Add Key</strong> button and select <strong>Create new key</strong>. At the prompt, make sure <strong>JSON</strong> is selected and click the <strong>Create</strong> button. This will create a .json file and download it to your computer.<br>
<img src="@source/en/storage/img/import_gcp-04.png" alt="Service account user page">
<img src="@source/en/storage/img/import_gcp-05.png" alt="Create private key dialog"></p>
</li>
</ol>
<p>To import the GCP account into Datahub, open the .json file in a text editor and paste the contents into the <strong>Service Account Credentials (JSON)</strong> text box in Datahub.<br>
<img src="@source/en/storage/img/import_gcp-06.png" alt="Import GCP storage dialog"></p>
</div></template>


